# Generated by Django 4.0.10 on 2024-09-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='texto',
            field=models.TextField(default='hola mundo'),
            preserve_default=False,
        ),
    ]
